### ISSUE TITLE
code have a bug, can't write expectation vcd file. could you repair it?

### ISSUE THREAD

**Issue by wind1206** [favorart/vcd-writer#1]
$timescale 1 ns $end
$date 2022-04-15 16:27:56 $end
$scope module a $end
$scope module b $end
$scope module c $end
$var integer 8 0 counter $end
$upscope $end
$upscope $end
$upscope $end
$enddefinitions $end
#0
$dumpvars
b0000
$end

![image](https://user-images.githubusercontent.com/68800734/163746191-f4f76c31-8d05-4cfa-bc3a-86c7bc05258a.png)

**Comment by favorart** [comment]
Hello, what code did you used to generate such a file? I'll try to fix this

**Comment by wind1206** [comment]
Quick Start example.
github.com/favorart/vcd-writer



---Original---
From: "Kirirll ***@***.***&gt;
Date: Mon, Apr 18, 2022 14:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [favorart/vcd-writer] code have a bug, can't write expectationvcd file. could you repair it? (Issue #1)




 
Hello, what code did you used to generate such a files? I'll try to fix this

**Comment by favorart** [comment]
Thank you for your feedback. I fixed bug
